// Everything that changes at publish time lives here, so nothing else in the site has to.
//
// The RELEASE block below is rewritten by `npm run release` in the app repo — it stamps the
// version, size and checksum of the installer it just built. Edit the values above it by hand.

export const DOMAIN = 'flintgrab.com'
export const CONTACT = `hello@${DOMAIN}`

export const PRICE = {
  amount: '$10',
  // "One time" rather than "lifetime" as the primary word: lifetime is what a subscription page
  // says when it wants credit for not being a subscription.
  term: 'one time',
  trialDays: 15,
} as const

// release:start — generated by `npm run release`, do not edit by hand
export const RELEASE = {
  version: '0.1.0',
  date: '2026-08-28',
  url: 'downloads/Flintgrab-Setup-0.1.0.exe',
  size: '180 MB',
  sha256: 'd30ea14dd08ed808dbf61e75a09fada183e320c4108b5c30695c4af62dea4778',
  requires: 'Windows 10 or 11, 64-bit',
  signed: false,
  notes: [
    { kind: 'Added', text: 'Paste-a-link downloading. One input that takes a video page, a playlist, a direct file link, or a magnet link.' },
    { kind: 'Added', text: 'Segmented transfers with byte-exact pause, resume, and crash recovery.' },
    { kind: 'Added', text: 'Adaptive stream handling for HLS and DASH, muxed without re-encoding.' },
    { kind: 'Added', text: 'Browser extension for Chrome, Edge and Brave, with an in-page badge on every video.' },
    { kind: 'Added', text: 'Torrent, magnet, FTP, FTPS and SFTP transfers through the same queue.' },
  ],
} as const
// release:end

export type ReleaseNote = (typeof RELEASE.notes)[number]
